---
abstract: 'grab all the details from your Amazon wishlist'
author:
  - 'Simon Wistow'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::Amazon::Wishlist
name: WWW-Amazon-Wishlist
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Getopt::Long: 0
  HTML::TreeBuilder: 0
  LWP::UserAgent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.601
